Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -36,7 +36,7 @@ jobs:
           mkdir -p ~/.ssh
           echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/auto-key.pem
           chmod 600 ~/.ssh/auto-key.pem
-          ssh-keygen -y -f ~/.ssh/auto-key.pem > ~/.sshkey.pub || echo "Invalid key"
+          ssh-keygen -y -f ~/.ssh/auto-key.pem > ~/.ssh/auto-key.pub || echo "Invalid key"
 
       - name: Add SSH Host Key to Known Hosts
         run: |
