Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -34,9 +34,9 @@ jobs:
       - name: Configure SSH Key
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/key.pem
-          chmod 600 ~/.ssh/key.pem
-          ssh-keygen -y -f ~/.ssh/key.pem > ~/.sshkey.pub || echo "Invalid key"
+          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/auto-key.pem
+          chmod 600 ~/.ssh/auto-key.pem
+          ssh-keygen -y -f ~/.ssh/auto-key.pem > ~/.sshkey.pub || echo "Invalid key"
 
       - name: Add SSH Host Key to Known Hosts
         run: |
